title: Ivan's Blog
url: "http://ivanshen.me"
baseurl: "/blog.ivan"

site_heading: >
    blog.ivan

email: iwshen11@gmail.com
author: Ivan Shen

description: >
    accent is, as Trump would put it, the best

copyright: Ivan Shen
intro: false         

permalink: /:title.html

comments: false

about_footer: false

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 7
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
######### Build Settings  ##########
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
